// Generated by tools/sync_ant_design_icons.py. DO NOT EDIT.
#include "antd_icons.h"

#include "generated/antd_pack_data.h"

#include <QFile>

#include <mutex>

int qInitResources_ant_design_icons();

namespace adqt::icons::antd {
namespace {

void ensureResources() {
  static bool initialized = false;
  if (!initialized) {
    ::qInitResources_ant_design_icons();
    initialized = true;
  }
}

IconRef makeRef(IconTheme theme, const char* name, const IconColorOverrides& colors) {
  ensureAntdRegistered();
  IconRef ref;
  ref.id.pack = QStringLiteral("antd");
  ref.id.theme = theme;
  ref.id.name = QString::fromLatin1(name);
  ref.colors = colors;
  return ref;
}

bool loadDefinition(const detail::PackEntry& entry, IconDefinition* definition) {
  QFile file(QString::fromLatin1(entry.qrcPath));
  if (!file.open(QIODevice::ReadOnly)) {
    return false;
  }
  IconDefinition def;
  def.id.pack = QStringLiteral("antd");
  def.id.theme = entry.theme;
  def.id.name = QString::fromLatin1(entry.name);
  def.model = entry.model;
  def.svgTemplate = file.readAll();
  if (!def.isValid()) {
    return false;
  }
  *definition = def;
  return true;
}

}  // namespace

const char* version() {
  return ADQT_ANTD_ICONS_VERSION_STR;
}

void registerAntdPack(IconRegistry& registry) {
  ensureResources();
  for (int index = 0; index < detail::packEntryCount(); ++index) {
    IconDefinition definition;
    if (loadDefinition(detail::packEntries()[index], &definition)) {
      registry.registerIcon(definition);
    }
  }
}

void ensureAntdRegistered() {
  static std::once_flag once;
  std::call_once(once, []() { registerAntdPack(defaultRegistry()); });
}

namespace outlined {
IconRef AccountBook(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "account-book", colors);
}

IconRef Aim(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "aim", colors);
}

IconRef Alert(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "alert", colors);
}

IconRef Alibaba(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "alibaba", colors);
}

IconRef AlignCenter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "align-center", colors);
}

IconRef AlignLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "align-left", colors);
}

IconRef AlignRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "align-right", colors);
}

IconRef Alipay(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "alipay", colors);
}

IconRef AlipayCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "alipay-circle", colors);
}

IconRef Aliwangwang(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "aliwangwang", colors);
}

IconRef Aliyun(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "aliyun", colors);
}

IconRef Amazon(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "amazon", colors);
}

IconRef Android(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "android", colors);
}

IconRef AntCloud(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ant-cloud", colors);
}

IconRef AntDesign(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ant-design", colors);
}

IconRef Apartment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "apartment", colors);
}

IconRef Api(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "api", colors);
}

IconRef Apple(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "apple", colors);
}

IconRef Appstore(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "appstore", colors);
}

IconRef AppstoreAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "appstore-add", colors);
}

IconRef AreaChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "area-chart", colors);
}

IconRef ArrowDown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "arrow-down", colors);
}

IconRef ArrowLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "arrow-left", colors);
}

IconRef ArrowRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "arrow-right", colors);
}

IconRef ArrowUp(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "arrow-up", colors);
}

IconRef ArrowsAlt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "arrows-alt", colors);
}

IconRef Audio(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "audio", colors);
}

IconRef AudioMuted(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "audio-muted", colors);
}

IconRef Audit(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "audit", colors);
}

IconRef Backward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "backward", colors);
}

IconRef Baidu(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "baidu", colors);
}

IconRef Bank(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bank", colors);
}

IconRef BarChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bar-chart", colors);
}

IconRef Barcode(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "barcode", colors);
}

IconRef Bars(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bars", colors);
}

IconRef Behance(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "behance", colors);
}

IconRef BehanceSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "behance-square", colors);
}

IconRef Bell(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bell", colors);
}

IconRef BgColors(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bg-colors", colors);
}

IconRef Bilibili(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bilibili", colors);
}

IconRef Block(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "block", colors);
}

IconRef Bold(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bold", colors);
}

IconRef Book(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "book", colors);
}

IconRef Border(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border", colors);
}

IconRef BorderBottom(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-bottom", colors);
}

IconRef BorderHorizontal(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-horizontal", colors);
}

IconRef BorderInner(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-inner", colors);
}

IconRef BorderLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-left", colors);
}

IconRef BorderOuter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-outer", colors);
}

IconRef BorderRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-right", colors);
}

IconRef BorderTop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-top", colors);
}

IconRef BorderVerticle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "border-verticle", colors);
}

IconRef BorderlessTable(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "borderless-table", colors);
}

IconRef BoxPlot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "box-plot", colors);
}

IconRef Branches(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "branches", colors);
}

IconRef Bug(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bug", colors);
}

IconRef Build(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "build", colors);
}

IconRef Bulb(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "bulb", colors);
}

IconRef Calculator(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "calculator", colors);
}

IconRef Calendar(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "calendar", colors);
}

IconRef Camera(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "camera", colors);
}

IconRef Car(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "car", colors);
}

IconRef CaretDown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "caret-down", colors);
}

IconRef CaretLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "caret-left", colors);
}

IconRef CaretRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "caret-right", colors);
}

IconRef CaretUp(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "caret-up", colors);
}

IconRef CarryOut(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "carry-out", colors);
}

IconRef Check(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "check", colors);
}

IconRef CheckCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "check-circle", colors);
}

IconRef CheckSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "check-square", colors);
}

IconRef Chrome(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "chrome", colors);
}

IconRef Ci(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ci", colors);
}

IconRef CiCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ci-circle", colors);
}

IconRef Clear(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "clear", colors);
}

IconRef ClockCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "clock-circle", colors);
}

IconRef Close(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "close", colors);
}

IconRef CloseCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "close-circle", colors);
}

IconRef CloseSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "close-square", colors);
}

IconRef Cloud(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "cloud", colors);
}

IconRef CloudDownload(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "cloud-download", colors);
}

IconRef CloudServer(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "cloud-server", colors);
}

IconRef CloudSync(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "cloud-sync", colors);
}

IconRef CloudUpload(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "cloud-upload", colors);
}

IconRef Cluster(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "cluster", colors);
}

IconRef Code(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "code", colors);
}

IconRef CodeSandbox(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "code-sandbox", colors);
}

IconRef Codepen(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "codepen", colors);
}

IconRef CodepenCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "codepen-circle", colors);
}

IconRef Coffee(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "coffee", colors);
}

IconRef ColumnHeight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "column-height", colors);
}

IconRef ColumnWidth(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "column-width", colors);
}

IconRef Comment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "comment", colors);
}

IconRef Compass(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "compass", colors);
}

IconRef Compress(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "compress", colors);
}

IconRef ConsoleSql(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "console-sql", colors);
}

IconRef Contacts(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "contacts", colors);
}

IconRef Container(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "container", colors);
}

IconRef Control(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "control", colors);
}

IconRef Copy(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "copy", colors);
}

IconRef Copyright(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "copyright", colors);
}

IconRef CopyrightCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "copyright-circle", colors);
}

IconRef CreditCard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "credit-card", colors);
}

IconRef Crown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "crown", colors);
}

IconRef CustomerService(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "customer-service", colors);
}

IconRef Dash(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dash", colors);
}

IconRef Dashboard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dashboard", colors);
}

IconRef Database(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "database", colors);
}

IconRef Delete(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "delete", colors);
}

IconRef DeleteColumn(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "delete-column", colors);
}

IconRef DeleteRow(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "delete-row", colors);
}

IconRef DeliveredProcedure(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "delivered-procedure", colors);
}

IconRef DeploymentUnit(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "deployment-unit", colors);
}

IconRef Desktop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "desktop", colors);
}

IconRef Diff(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "diff", colors);
}

IconRef Dingding(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dingding", colors);
}

IconRef Dingtalk(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dingtalk", colors);
}

IconRef Disconnect(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "disconnect", colors);
}

IconRef Discord(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "discord", colors);
}

IconRef Dislike(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dislike", colors);
}

IconRef Docker(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "docker", colors);
}

IconRef Dollar(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dollar", colors);
}

IconRef DollarCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dollar-circle", colors);
}

IconRef DotChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dot-chart", colors);
}

IconRef DotNet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dot-net", colors);
}

IconRef DoubleLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "double-left", colors);
}

IconRef DoubleRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "double-right", colors);
}

IconRef Down(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "down", colors);
}

IconRef DownCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "down-circle", colors);
}

IconRef DownSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "down-square", colors);
}

IconRef Download(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "download", colors);
}

IconRef Drag(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "drag", colors);
}

IconRef Dribbble(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dribbble", colors);
}

IconRef DribbbleSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dribbble-square", colors);
}

IconRef Dropbox(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "dropbox", colors);
}

IconRef Edit(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "edit", colors);
}

IconRef Ellipsis(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ellipsis", colors);
}

IconRef Enter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "enter", colors);
}

IconRef Environment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "environment", colors);
}

IconRef Euro(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "euro", colors);
}

IconRef EuroCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "euro-circle", colors);
}

IconRef Exception(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "exception", colors);
}

IconRef Exclamation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "exclamation", colors);
}

IconRef ExclamationCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "exclamation-circle", colors);
}

IconRef Expand(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "expand", colors);
}

IconRef ExpandAlt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "expand-alt", colors);
}

IconRef Experiment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "experiment", colors);
}

IconRef Export(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "export", colors);
}

IconRef Eye(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "eye", colors);
}

IconRef EyeInvisible(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "eye-invisible", colors);
}

IconRef Facebook(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "facebook", colors);
}

IconRef Fall(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fall", colors);
}

IconRef FastBackward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fast-backward", colors);
}

IconRef FastForward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fast-forward", colors);
}

IconRef FieldBinary(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "field-binary", colors);
}

IconRef FieldNumber(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "field-number", colors);
}

IconRef FieldString(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "field-string", colors);
}

IconRef FieldTime(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "field-time", colors);
}

IconRef File(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file", colors);
}

IconRef FileAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-add", colors);
}

IconRef FileDone(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-done", colors);
}

IconRef FileExcel(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-excel", colors);
}

IconRef FileExclamation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-exclamation", colors);
}

IconRef FileGif(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-gif", colors);
}

IconRef FileImage(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-image", colors);
}

IconRef FileJpg(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-jpg", colors);
}

IconRef FileMarkdown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-markdown", colors);
}

IconRef FilePdf(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-pdf", colors);
}

IconRef FilePpt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-ppt", colors);
}

IconRef FileProtect(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-protect", colors);
}

IconRef FileSearch(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-search", colors);
}

IconRef FileSync(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-sync", colors);
}

IconRef FileText(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-text", colors);
}

IconRef FileUnknown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-unknown", colors);
}

IconRef FileWord(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-word", colors);
}

IconRef FileZip(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "file-zip", colors);
}

IconRef Filter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "filter", colors);
}

IconRef Fire(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fire", colors);
}

IconRef Flag(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "flag", colors);
}

IconRef Folder(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "folder", colors);
}

IconRef FolderAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "folder-add", colors);
}

IconRef FolderOpen(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "folder-open", colors);
}

IconRef FolderView(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "folder-view", colors);
}

IconRef FontColors(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "font-colors", colors);
}

IconRef FontSize(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "font-size", colors);
}

IconRef Fork(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fork", colors);
}

IconRef Form(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "form", colors);
}

IconRef FormatPainter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "format-painter", colors);
}

IconRef Forward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "forward", colors);
}

IconRef Frown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "frown", colors);
}

IconRef Fullscreen(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fullscreen", colors);
}

IconRef FullscreenExit(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fullscreen-exit", colors);
}

IconRef Function(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "function", colors);
}

IconRef Fund(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fund", colors);
}

IconRef FundProjectionScreen(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fund-projection-screen", colors);
}

IconRef FundView(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "fund-view", colors);
}

IconRef FunnelPlot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "funnel-plot", colors);
}

IconRef Gateway(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "gateway", colors);
}

IconRef Gif(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "gif", colors);
}

IconRef Gift(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "gift", colors);
}

IconRef Github(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "github", colors);
}

IconRef Gitlab(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "gitlab", colors);
}

IconRef Global(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "global", colors);
}

IconRef Gold(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "gold", colors);
}

IconRef Google(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "google", colors);
}

IconRef GooglePlus(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "google-plus", colors);
}

IconRef Group(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "group", colors);
}

IconRef HarmonyOS(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "harmony-o-s", colors);
}

IconRef Hdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "hdd", colors);
}

IconRef Heart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "heart", colors);
}

IconRef HeatMap(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "heat-map", colors);
}

IconRef Highlight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "highlight", colors);
}

IconRef History(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "history", colors);
}

IconRef Holder(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "holder", colors);
}

IconRef Home(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "home", colors);
}

IconRef Hourglass(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "hourglass", colors);
}

IconRef Html5(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "html5", colors);
}

IconRef Idcard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "idcard", colors);
}

IconRef Ie(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ie", colors);
}

IconRef Import(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "import", colors);
}

IconRef Inbox(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "inbox", colors);
}

IconRef Info(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "info", colors);
}

IconRef InfoCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "info-circle", colors);
}

IconRef InsertRowAbove(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "insert-row-above", colors);
}

IconRef InsertRowBelow(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "insert-row-below", colors);
}

IconRef InsertRowLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "insert-row-left", colors);
}

IconRef InsertRowRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "insert-row-right", colors);
}

IconRef Instagram(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "instagram", colors);
}

IconRef Insurance(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "insurance", colors);
}

IconRef Interaction(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "interaction", colors);
}

IconRef IssuesClose(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "issues-close", colors);
}

IconRef Italic(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "italic", colors);
}

IconRef Java(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "java", colors);
}

IconRef JavaScript(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "java-script", colors);
}

IconRef Key(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "key", colors);
}

IconRef Kubernetes(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "kubernetes", colors);
}

IconRef Laptop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "laptop", colors);
}

IconRef Layout(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "layout", colors);
}

IconRef Left(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "left", colors);
}

IconRef LeftCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "left-circle", colors);
}

IconRef LeftSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "left-square", colors);
}

IconRef Like(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "like", colors);
}

IconRef Line(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "line", colors);
}

IconRef LineChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "line-chart", colors);
}

IconRef LineHeight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "line-height", colors);
}

IconRef Link(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "link", colors);
}

IconRef Linkedin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "linkedin", colors);
}

IconRef Linux(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "linux", colors);
}

IconRef Loading(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "loading", colors);
}

IconRef Loading3Quarters(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "loading-3-quarters", colors);
}

IconRef Lock(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "lock", colors);
}

IconRef Login(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "login", colors);
}

IconRef Logout(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "logout", colors);
}

IconRef MacCommand(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "mac-command", colors);
}

IconRef Mail(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "mail", colors);
}

IconRef Man(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "man", colors);
}

IconRef MedicineBox(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "medicine-box", colors);
}

IconRef Medium(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "medium", colors);
}

IconRef MediumWorkmark(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "medium-workmark", colors);
}

IconRef Meh(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "meh", colors);
}

IconRef Menu(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "menu", colors);
}

IconRef MenuFold(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "menu-fold", colors);
}

IconRef MenuUnfold(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "menu-unfold", colors);
}

IconRef Merge(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "merge", colors);
}

IconRef MergeCells(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "merge-cells", colors);
}

IconRef Message(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "message", colors);
}

IconRef Minus(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "minus", colors);
}

IconRef MinusCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "minus-circle", colors);
}

IconRef MinusSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "minus-square", colors);
}

IconRef Mobile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "mobile", colors);
}

IconRef MoneyCollect(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "money-collect", colors);
}

IconRef Monitor(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "monitor", colors);
}

IconRef Moon(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "moon", colors);
}

IconRef More(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "more", colors);
}

IconRef Muted(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "muted", colors);
}

IconRef NodeCollapse(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "node-collapse", colors);
}

IconRef NodeExpand(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "node-expand", colors);
}

IconRef NodeIndex(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "node-index", colors);
}

IconRef Notification(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "notification", colors);
}

IconRef Number(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "number", colors);
}

IconRef OneToOne(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "one-to-one", colors);
}

IconRef OpenAI(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "open-a-i", colors);
}

IconRef OrderedList(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ordered-list", colors);
}

IconRef PaperClip(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "paper-clip", colors);
}

IconRef Partition(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "partition", colors);
}

IconRef Pause(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pause", colors);
}

IconRef PauseCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pause-circle", colors);
}

IconRef PayCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pay-circle", colors);
}

IconRef Percentage(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "percentage", colors);
}

IconRef Phone(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "phone", colors);
}

IconRef PicCenter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pic-center", colors);
}

IconRef PicLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pic-left", colors);
}

IconRef PicRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pic-right", colors);
}

IconRef Picture(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "picture", colors);
}

IconRef PieChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pie-chart", colors);
}

IconRef Pinterest(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pinterest", colors);
}

IconRef PlayCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "play-circle", colors);
}

IconRef PlaySquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "play-square", colors);
}

IconRef Plus(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "plus", colors);
}

IconRef PlusCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "plus-circle", colors);
}

IconRef PlusSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "plus-square", colors);
}

IconRef Pound(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pound", colors);
}

IconRef PoundCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pound-circle", colors);
}

IconRef Poweroff(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "poweroff", colors);
}

IconRef Printer(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "printer", colors);
}

IconRef Product(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "product", colors);
}

IconRef Profile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "profile", colors);
}

IconRef Project(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "project", colors);
}

IconRef PropertySafety(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "property-safety", colors);
}

IconRef PullRequest(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pull-request", colors);
}

IconRef Pushpin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "pushpin", colors);
}

IconRef Python(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "python", colors);
}

IconRef Qq(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "qq", colors);
}

IconRef Qrcode(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "qrcode", colors);
}

IconRef Question(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "question", colors);
}

IconRef QuestionCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "question-circle", colors);
}

IconRef RadarChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "radar-chart", colors);
}

IconRef RadiusBottomleft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "radius-bottomleft", colors);
}

IconRef RadiusBottomright(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "radius-bottomright", colors);
}

IconRef RadiusSetting(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "radius-setting", colors);
}

IconRef RadiusUpleft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "radius-upleft", colors);
}

IconRef RadiusUpright(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "radius-upright", colors);
}

IconRef Read(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "read", colors);
}

IconRef Reconciliation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "reconciliation", colors);
}

IconRef RedEnvelope(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "red-envelope", colors);
}

IconRef Reddit(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "reddit", colors);
}

IconRef Redo(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "redo", colors);
}

IconRef Reload(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "reload", colors);
}

IconRef Rest(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "rest", colors);
}

IconRef Retweet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "retweet", colors);
}

IconRef Right(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "right", colors);
}

IconRef RightCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "right-circle", colors);
}

IconRef RightSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "right-square", colors);
}

IconRef Rise(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "rise", colors);
}

IconRef Robot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "robot", colors);
}

IconRef Rocket(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "rocket", colors);
}

IconRef Rollback(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "rollback", colors);
}

IconRef RotateLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "rotate-left", colors);
}

IconRef RotateRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "rotate-right", colors);
}

IconRef Ruby(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ruby", colors);
}

IconRef Safety(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "safety", colors);
}

IconRef SafetyCertificate(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "safety-certificate", colors);
}

IconRef Save(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "save", colors);
}

IconRef Scan(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "scan", colors);
}

IconRef Schedule(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "schedule", colors);
}

IconRef Scissor(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "scissor", colors);
}

IconRef Search(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "search", colors);
}

IconRef SecurityScan(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "security-scan", colors);
}

IconRef Select(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "select", colors);
}

IconRef Send(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "send", colors);
}

IconRef Setting(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "setting", colors);
}

IconRef Shake(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "shake", colors);
}

IconRef ShareAlt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "share-alt", colors);
}

IconRef Shop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "shop", colors);
}

IconRef Shopping(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "shopping", colors);
}

IconRef ShoppingCart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "shopping-cart", colors);
}

IconRef Shrink(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "shrink", colors);
}

IconRef Signature(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "signature", colors);
}

IconRef Sisternode(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sisternode", colors);
}

IconRef Sketch(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sketch", colors);
}

IconRef Skin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "skin", colors);
}

IconRef Skype(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "skype", colors);
}

IconRef Slack(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "slack", colors);
}

IconRef SlackSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "slack-square", colors);
}

IconRef Sliders(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sliders", colors);
}

IconRef SmallDash(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "small-dash", colors);
}

IconRef Smile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "smile", colors);
}

IconRef Snippets(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "snippets", colors);
}

IconRef Solution(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "solution", colors);
}

IconRef SortAscending(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sort-ascending", colors);
}

IconRef SortDescending(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sort-descending", colors);
}

IconRef Sound(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sound", colors);
}

IconRef SplitCells(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "split-cells", colors);
}

IconRef Spotify(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "spotify", colors);
}

IconRef Star(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "star", colors);
}

IconRef StepBackward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "step-backward", colors);
}

IconRef StepForward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "step-forward", colors);
}

IconRef Stock(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "stock", colors);
}

IconRef Stop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "stop", colors);
}

IconRef Strikethrough(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "strikethrough", colors);
}

IconRef Subnode(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "subnode", colors);
}

IconRef Sun(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sun", colors);
}

IconRef Swap(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "swap", colors);
}

IconRef SwapLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "swap-left", colors);
}

IconRef SwapRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "swap-right", colors);
}

IconRef Switcher(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "switcher", colors);
}

IconRef Sync(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "sync", colors);
}

IconRef Table(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "table", colors);
}

IconRef Tablet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "tablet", colors);
}

IconRef Tag(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "tag", colors);
}

IconRef Tags(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "tags", colors);
}

IconRef Taobao(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "taobao", colors);
}

IconRef TaobaoCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "taobao-circle", colors);
}

IconRef Team(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "team", colors);
}

IconRef Thunderbolt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "thunderbolt", colors);
}

IconRef TikTok(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "tik-tok", colors);
}

IconRef ToTop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "to-top", colors);
}

IconRef Tool(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "tool", colors);
}

IconRef Trademark(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "trademark", colors);
}

IconRef TrademarkCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "trademark-circle", colors);
}

IconRef Transaction(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "transaction", colors);
}

IconRef Translation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "translation", colors);
}

IconRef Trophy(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "trophy", colors);
}

IconRef Truck(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "truck", colors);
}

IconRef Twitch(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "twitch", colors);
}

IconRef Twitter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "twitter", colors);
}

IconRef Underline(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "underline", colors);
}

IconRef Undo(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "undo", colors);
}

IconRef Ungroup(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "ungroup", colors);
}

IconRef Unlock(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "unlock", colors);
}

IconRef UnorderedList(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "unordered-list", colors);
}

IconRef Up(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "up", colors);
}

IconRef UpCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "up-circle", colors);
}

IconRef UpSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "up-square", colors);
}

IconRef Upload(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "upload", colors);
}

IconRef Usb(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "usb", colors);
}

IconRef User(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "user", colors);
}

IconRef UserAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "user-add", colors);
}

IconRef UserDelete(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "user-delete", colors);
}

IconRef UserSwitch(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "user-switch", colors);
}

IconRef UsergroupAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "usergroup-add", colors);
}

IconRef UsergroupDelete(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "usergroup-delete", colors);
}

IconRef Verified(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "verified", colors);
}

IconRef VerticalAlignBottom(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "vertical-align-bottom", colors);
}

IconRef VerticalAlignMiddle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "vertical-align-middle", colors);
}

IconRef VerticalAlignTop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "vertical-align-top", colors);
}

IconRef VerticalLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "vertical-left", colors);
}

IconRef VerticalRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "vertical-right", colors);
}

IconRef VideoCamera(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "video-camera", colors);
}

IconRef VideoCameraAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "video-camera-add", colors);
}

IconRef Wallet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "wallet", colors);
}

IconRef Warning(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "warning", colors);
}

IconRef Wechat(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "wechat", colors);
}

IconRef WechatWork(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "wechat-work", colors);
}

IconRef Weibo(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "weibo", colors);
}

IconRef WeiboCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "weibo-circle", colors);
}

IconRef WeiboSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "weibo-square", colors);
}

IconRef WhatsApp(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "whats-app", colors);
}

IconRef Wifi(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "wifi", colors);
}

IconRef Windows(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "windows", colors);
}

IconRef Woman(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "woman", colors);
}

IconRef X(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "x", colors);
}

IconRef Yahoo(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "yahoo", colors);
}

IconRef Youtube(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "youtube", colors);
}

IconRef Yuque(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "yuque", colors);
}

IconRef Zhihu(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "zhihu", colors);
}

IconRef ZoomIn(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "zoom-in", colors);
}

IconRef ZoomOut(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Outlined, "zoom-out", colors);
}

}  // namespace outlined

namespace filled {
IconRef AccountBook(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "account-book", colors);
}

IconRef Alert(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "alert", colors);
}

IconRef AlipayCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "alipay-circle", colors);
}

IconRef AlipaySquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "alipay-square", colors);
}

IconRef Aliwangwang(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "aliwangwang", colors);
}

IconRef AmazonCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "amazon-circle", colors);
}

IconRef AmazonSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "amazon-square", colors);
}

IconRef Android(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "android", colors);
}

IconRef Api(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "api", colors);
}

IconRef Apple(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "apple", colors);
}

IconRef Appstore(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "appstore", colors);
}

IconRef Audio(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "audio", colors);
}

IconRef Backward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "backward", colors);
}

IconRef Bank(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "bank", colors);
}

IconRef BehanceCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "behance-circle", colors);
}

IconRef BehanceSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "behance-square", colors);
}

IconRef Bell(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "bell", colors);
}

IconRef Bilibili(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "bilibili", colors);
}

IconRef Book(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "book", colors);
}

IconRef BoxPlot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "box-plot", colors);
}

IconRef Bug(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "bug", colors);
}

IconRef Build(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "build", colors);
}

IconRef Bulb(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "bulb", colors);
}

IconRef Calculator(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "calculator", colors);
}

IconRef Calendar(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "calendar", colors);
}

IconRef Camera(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "camera", colors);
}

IconRef Car(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "car", colors);
}

IconRef CaretDown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "caret-down", colors);
}

IconRef CaretLeft(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "caret-left", colors);
}

IconRef CaretRight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "caret-right", colors);
}

IconRef CaretUp(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "caret-up", colors);
}

IconRef CarryOut(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "carry-out", colors);
}

IconRef CheckCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "check-circle", colors);
}

IconRef CheckSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "check-square", colors);
}

IconRef Chrome(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "chrome", colors);
}

IconRef CiCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "ci-circle", colors);
}

IconRef ClockCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "clock-circle", colors);
}

IconRef CloseCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "close-circle", colors);
}

IconRef CloseSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "close-square", colors);
}

IconRef Cloud(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "cloud", colors);
}

IconRef Code(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "code", colors);
}

IconRef CodeSandboxCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "code-sandbox-circle", colors);
}

IconRef CodeSandboxSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "code-sandbox-square", colors);
}

IconRef CodepenCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "codepen-circle", colors);
}

IconRef CodepenSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "codepen-square", colors);
}

IconRef Compass(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "compass", colors);
}

IconRef Contacts(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "contacts", colors);
}

IconRef Container(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "container", colors);
}

IconRef Control(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "control", colors);
}

IconRef Copy(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "copy", colors);
}

IconRef CopyrightCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "copyright-circle", colors);
}

IconRef CreditCard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "credit-card", colors);
}

IconRef Crown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "crown", colors);
}

IconRef CustomerService(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "customer-service", colors);
}

IconRef Dashboard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dashboard", colors);
}

IconRef Database(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "database", colors);
}

IconRef Delete(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "delete", colors);
}

IconRef Diff(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "diff", colors);
}

IconRef DingtalkCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dingtalk-circle", colors);
}

IconRef DingtalkSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dingtalk-square", colors);
}

IconRef Discord(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "discord", colors);
}

IconRef Dislike(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dislike", colors);
}

IconRef DollarCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dollar-circle", colors);
}

IconRef DownCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "down-circle", colors);
}

IconRef DownSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "down-square", colors);
}

IconRef DribbbleCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dribbble-circle", colors);
}

IconRef DribbbleSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dribbble-square", colors);
}

IconRef DropboxCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dropbox-circle", colors);
}

IconRef DropboxSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "dropbox-square", colors);
}

IconRef Edit(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "edit", colors);
}

IconRef Environment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "environment", colors);
}

IconRef EuroCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "euro-circle", colors);
}

IconRef ExclamationCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "exclamation-circle", colors);
}

IconRef Experiment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "experiment", colors);
}

IconRef Eye(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "eye", colors);
}

IconRef EyeInvisible(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "eye-invisible", colors);
}

IconRef Facebook(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "facebook", colors);
}

IconRef FastBackward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "fast-backward", colors);
}

IconRef FastForward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "fast-forward", colors);
}

IconRef File(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file", colors);
}

IconRef FileAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-add", colors);
}

IconRef FileExcel(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-excel", colors);
}

IconRef FileExclamation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-exclamation", colors);
}

IconRef FileImage(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-image", colors);
}

IconRef FileMarkdown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-markdown", colors);
}

IconRef FilePdf(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-pdf", colors);
}

IconRef FilePpt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-ppt", colors);
}

IconRef FileText(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-text", colors);
}

IconRef FileUnknown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-unknown", colors);
}

IconRef FileWord(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-word", colors);
}

IconRef FileZip(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "file-zip", colors);
}

IconRef Filter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "filter", colors);
}

IconRef Fire(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "fire", colors);
}

IconRef Flag(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "flag", colors);
}

IconRef Folder(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "folder", colors);
}

IconRef FolderAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "folder-add", colors);
}

IconRef FolderOpen(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "folder-open", colors);
}

IconRef FormatPainter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "format-painter", colors);
}

IconRef Forward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "forward", colors);
}

IconRef Frown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "frown", colors);
}

IconRef Fund(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "fund", colors);
}

IconRef FunnelPlot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "funnel-plot", colors);
}

IconRef Gift(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "gift", colors);
}

IconRef Github(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "github", colors);
}

IconRef Gitlab(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "gitlab", colors);
}

IconRef Gold(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "gold", colors);
}

IconRef Golden(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "golden", colors);
}

IconRef GoogleCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "google-circle", colors);
}

IconRef GooglePlusCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "google-plus-circle", colors);
}

IconRef GooglePlusSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "google-plus-square", colors);
}

IconRef GoogleSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "google-square", colors);
}

IconRef Hdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "hdd", colors);
}

IconRef Heart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "heart", colors);
}

IconRef Highlight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "highlight", colors);
}

IconRef Home(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "home", colors);
}

IconRef Hourglass(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "hourglass", colors);
}

IconRef Html5(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "html5", colors);
}

IconRef Idcard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "idcard", colors);
}

IconRef IeCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "ie-circle", colors);
}

IconRef IeSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "ie-square", colors);
}

IconRef InfoCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "info-circle", colors);
}

IconRef Instagram(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "instagram", colors);
}

IconRef Insurance(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "insurance", colors);
}

IconRef Interaction(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "interaction", colors);
}

IconRef Layout(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "layout", colors);
}

IconRef LeftCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "left-circle", colors);
}

IconRef LeftSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "left-square", colors);
}

IconRef Like(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "like", colors);
}

IconRef Linkedin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "linkedin", colors);
}

IconRef Lock(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "lock", colors);
}

IconRef MacCommand(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "mac-command", colors);
}

IconRef Mail(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "mail", colors);
}

IconRef MedicineBox(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "medicine-box", colors);
}

IconRef MediumCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "medium-circle", colors);
}

IconRef MediumSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "medium-square", colors);
}

IconRef Meh(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "meh", colors);
}

IconRef Merge(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "merge", colors);
}

IconRef Message(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "message", colors);
}

IconRef MinusCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "minus-circle", colors);
}

IconRef MinusSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "minus-square", colors);
}

IconRef Mobile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "mobile", colors);
}

IconRef MoneyCollect(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "money-collect", colors);
}

IconRef Moon(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "moon", colors);
}

IconRef Muted(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "muted", colors);
}

IconRef Notification(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "notification", colors);
}

IconRef OpenAI(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "open-a-i", colors);
}

IconRef PauseCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "pause-circle", colors);
}

IconRef PayCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "pay-circle", colors);
}

IconRef Phone(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "phone", colors);
}

IconRef Picture(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "picture", colors);
}

IconRef PieChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "pie-chart", colors);
}

IconRef Pinterest(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "pinterest", colors);
}

IconRef PlayCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "play-circle", colors);
}

IconRef PlaySquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "play-square", colors);
}

IconRef PlusCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "plus-circle", colors);
}

IconRef PlusSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "plus-square", colors);
}

IconRef PoundCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "pound-circle", colors);
}

IconRef Printer(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "printer", colors);
}

IconRef Product(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "product", colors);
}

IconRef Profile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "profile", colors);
}

IconRef Project(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "project", colors);
}

IconRef PropertySafety(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "property-safety", colors);
}

IconRef Pushpin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "pushpin", colors);
}

IconRef QqCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "qq-circle", colors);
}

IconRef QqSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "qq-square", colors);
}

IconRef QuestionCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "question-circle", colors);
}

IconRef Read(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "read", colors);
}

IconRef Reconciliation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "reconciliation", colors);
}

IconRef RedEnvelope(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "red-envelope", colors);
}

IconRef RedditCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "reddit-circle", colors);
}

IconRef RedditSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "reddit-square", colors);
}

IconRef Rest(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "rest", colors);
}

IconRef RightCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "right-circle", colors);
}

IconRef RightSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "right-square", colors);
}

IconRef Robot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "robot", colors);
}

IconRef Rocket(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "rocket", colors);
}

IconRef SafetyCertificate(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "safety-certificate", colors);
}

IconRef Save(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "save", colors);
}

IconRef Schedule(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "schedule", colors);
}

IconRef SecurityScan(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "security-scan", colors);
}

IconRef Setting(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "setting", colors);
}

IconRef Shop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "shop", colors);
}

IconRef Shopping(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "shopping", colors);
}

IconRef Signal(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "signal", colors);
}

IconRef Signature(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "signature", colors);
}

IconRef SketchCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "sketch-circle", colors);
}

IconRef SketchSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "sketch-square", colors);
}

IconRef Skin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "skin", colors);
}

IconRef Skype(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "skype", colors);
}

IconRef SlackCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "slack-circle", colors);
}

IconRef SlackSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "slack-square", colors);
}

IconRef Sliders(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "sliders", colors);
}

IconRef Smile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "smile", colors);
}

IconRef Snippets(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "snippets", colors);
}

IconRef Sound(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "sound", colors);
}

IconRef Spotify(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "spotify", colors);
}

IconRef Star(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "star", colors);
}

IconRef StepBackward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "step-backward", colors);
}

IconRef StepForward(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "step-forward", colors);
}

IconRef Stop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "stop", colors);
}

IconRef Sun(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "sun", colors);
}

IconRef Switcher(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "switcher", colors);
}

IconRef Tablet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "tablet", colors);
}

IconRef Tag(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "tag", colors);
}

IconRef Tags(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "tags", colors);
}

IconRef TaobaoCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "taobao-circle", colors);
}

IconRef TaobaoSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "taobao-square", colors);
}

IconRef Thunderbolt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "thunderbolt", colors);
}

IconRef TikTok(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "tik-tok", colors);
}

IconRef Tool(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "tool", colors);
}

IconRef TrademarkCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "trademark-circle", colors);
}

IconRef Trophy(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "trophy", colors);
}

IconRef Truck(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "truck", colors);
}

IconRef Twitch(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "twitch", colors);
}

IconRef TwitterCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "twitter-circle", colors);
}

IconRef TwitterSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "twitter-square", colors);
}

IconRef Unlock(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "unlock", colors);
}

IconRef UpCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "up-circle", colors);
}

IconRef UpSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "up-square", colors);
}

IconRef Usb(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "usb", colors);
}

IconRef VideoCamera(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "video-camera", colors);
}

IconRef Wallet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "wallet", colors);
}

IconRef Warning(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "warning", colors);
}

IconRef Wechat(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "wechat", colors);
}

IconRef WechatWork(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "wechat-work", colors);
}

IconRef WeiboCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "weibo-circle", colors);
}

IconRef WeiboSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "weibo-square", colors);
}

IconRef Windows(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "windows", colors);
}

IconRef X(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "x", colors);
}

IconRef Yahoo(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "yahoo", colors);
}

IconRef Youtube(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "youtube", colors);
}

IconRef Yuque(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "yuque", colors);
}

IconRef ZhihuCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "zhihu-circle", colors);
}

IconRef ZhihuSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::Filled, "zhihu-square", colors);
}

}  // namespace filled

namespace twotone {
IconRef AccountBook(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "account-book", colors);
}

IconRef Alert(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "alert", colors);
}

IconRef Api(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "api", colors);
}

IconRef Appstore(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "appstore", colors);
}

IconRef Audio(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "audio", colors);
}

IconRef Bank(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "bank", colors);
}

IconRef Bell(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "bell", colors);
}

IconRef Book(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "book", colors);
}

IconRef BoxPlot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "box-plot", colors);
}

IconRef Bug(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "bug", colors);
}

IconRef Build(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "build", colors);
}

IconRef Bulb(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "bulb", colors);
}

IconRef Calculator(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "calculator", colors);
}

IconRef Calendar(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "calendar", colors);
}

IconRef Camera(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "camera", colors);
}

IconRef Car(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "car", colors);
}

IconRef CarryOut(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "carry-out", colors);
}

IconRef CheckCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "check-circle", colors);
}

IconRef CheckSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "check-square", colors);
}

IconRef Ci(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "ci", colors);
}

IconRef CiCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "ci-circle", colors);
}

IconRef ClockCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "clock-circle", colors);
}

IconRef CloseCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "close-circle", colors);
}

IconRef CloseSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "close-square", colors);
}

IconRef Cloud(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "cloud", colors);
}

IconRef Code(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "code", colors);
}

IconRef Compass(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "compass", colors);
}

IconRef Contacts(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "contacts", colors);
}

IconRef Container(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "container", colors);
}

IconRef Control(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "control", colors);
}

IconRef Copy(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "copy", colors);
}

IconRef Copyright(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "copyright", colors);
}

IconRef CopyrightCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "copyright-circle", colors);
}

IconRef CreditCard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "credit-card", colors);
}

IconRef Crown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "crown", colors);
}

IconRef CustomerService(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "customer-service", colors);
}

IconRef Dashboard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "dashboard", colors);
}

IconRef Database(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "database", colors);
}

IconRef Delete(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "delete", colors);
}

IconRef Diff(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "diff", colors);
}

IconRef Dislike(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "dislike", colors);
}

IconRef Dollar(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "dollar", colors);
}

IconRef DollarCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "dollar-circle", colors);
}

IconRef DownCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "down-circle", colors);
}

IconRef DownSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "down-square", colors);
}

IconRef Edit(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "edit", colors);
}

IconRef EmptySimple(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "empty-simple", colors);
}

IconRef Environment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "environment", colors);
}

IconRef Euro(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "euro", colors);
}

IconRef EuroCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "euro-circle", colors);
}

IconRef ExclamationCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "exclamation-circle", colors);
}

IconRef Experiment(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "experiment", colors);
}

IconRef Eye(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "eye", colors);
}

IconRef EyeInvisible(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "eye-invisible", colors);
}

IconRef File(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file", colors);
}

IconRef FileAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-add", colors);
}

IconRef FileExcel(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-excel", colors);
}

IconRef FileExclamation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-exclamation", colors);
}

IconRef FileImage(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-image", colors);
}

IconRef FileMarkdown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-markdown", colors);
}

IconRef FilePdf(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-pdf", colors);
}

IconRef FilePpt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-ppt", colors);
}

IconRef FileText(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-text", colors);
}

IconRef FileUnknown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-unknown", colors);
}

IconRef FileWord(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-word", colors);
}

IconRef FileZip(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "file-zip", colors);
}

IconRef Filter(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "filter", colors);
}

IconRef Fire(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "fire", colors);
}

IconRef Flag(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "flag", colors);
}

IconRef Folder(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "folder", colors);
}

IconRef FolderAdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "folder-add", colors);
}

IconRef FolderOpen(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "folder-open", colors);
}

IconRef Frown(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "frown", colors);
}

IconRef Fund(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "fund", colors);
}

IconRef FunnelPlot(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "funnel-plot", colors);
}

IconRef Gift(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "gift", colors);
}

IconRef Gold(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "gold", colors);
}

IconRef Hdd(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "hdd", colors);
}

IconRef Heart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "heart", colors);
}

IconRef Highlight(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "highlight", colors);
}

IconRef Home(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "home", colors);
}

IconRef Hourglass(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "hourglass", colors);
}

IconRef Html5(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "html5", colors);
}

IconRef Idcard(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "idcard", colors);
}

IconRef InfoCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "info-circle", colors);
}

IconRef Insurance(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "insurance", colors);
}

IconRef Interaction(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "interaction", colors);
}

IconRef Layout(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "layout", colors);
}

IconRef LeftCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "left-circle", colors);
}

IconRef LeftSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "left-square", colors);
}

IconRef Like(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "like", colors);
}

IconRef Lock(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "lock", colors);
}

IconRef Mail(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "mail", colors);
}

IconRef MedicineBox(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "medicine-box", colors);
}

IconRef Meh(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "meh", colors);
}

IconRef Message(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "message", colors);
}

IconRef MinusCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "minus-circle", colors);
}

IconRef MinusSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "minus-square", colors);
}

IconRef Mobile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "mobile", colors);
}

IconRef MoneyCollect(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "money-collect", colors);
}

IconRef Notification(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "notification", colors);
}

IconRef PauseCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "pause-circle", colors);
}

IconRef Phone(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "phone", colors);
}

IconRef Picture(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "picture", colors);
}

IconRef PieChart(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "pie-chart", colors);
}

IconRef PlayCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "play-circle", colors);
}

IconRef PlaySquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "play-square", colors);
}

IconRef PlusCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "plus-circle", colors);
}

IconRef PlusSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "plus-square", colors);
}

IconRef PoundCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "pound-circle", colors);
}

IconRef Printer(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "printer", colors);
}

IconRef Profile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "profile", colors);
}

IconRef Project(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "project", colors);
}

IconRef PropertySafety(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "property-safety", colors);
}

IconRef Pushpin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "pushpin", colors);
}

IconRef QuestionCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "question-circle", colors);
}

IconRef Reconciliation(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "reconciliation", colors);
}

IconRef RedEnvelope(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "red-envelope", colors);
}

IconRef Rest(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "rest", colors);
}

IconRef RightCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "right-circle", colors);
}

IconRef RightSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "right-square", colors);
}

IconRef Rocket(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "rocket", colors);
}

IconRef SafetyCertificate(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "safety-certificate", colors);
}

IconRef Save(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "save", colors);
}

IconRef Schedule(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "schedule", colors);
}

IconRef SecurityScan(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "security-scan", colors);
}

IconRef Setting(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "setting", colors);
}

IconRef Shop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "shop", colors);
}

IconRef Shopping(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "shopping", colors);
}

IconRef Skin(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "skin", colors);
}

IconRef Sliders(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "sliders", colors);
}

IconRef Smile(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "smile", colors);
}

IconRef Snippets(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "snippets", colors);
}

IconRef Sound(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "sound", colors);
}

IconRef Star(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "star", colors);
}

IconRef Stop(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "stop", colors);
}

IconRef Switcher(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "switcher", colors);
}

IconRef Tablet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "tablet", colors);
}

IconRef Tag(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "tag", colors);
}

IconRef Tags(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "tags", colors);
}

IconRef Thunderbolt(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "thunderbolt", colors);
}

IconRef Tool(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "tool", colors);
}

IconRef TrademarkCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "trademark-circle", colors);
}

IconRef Trophy(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "trophy", colors);
}

IconRef Unlock(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "unlock", colors);
}

IconRef UpCircle(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "up-circle", colors);
}

IconRef UpSquare(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "up-square", colors);
}

IconRef Usb(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "usb", colors);
}

IconRef VideoCamera(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "video-camera", colors);
}

IconRef Wallet(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "wallet", colors);
}

IconRef Warning(const IconColorOverrides& colors) {
  return makeRef(IconTheme::TwoTone, "warning", colors);
}

}  // namespace twotone

}  // namespace adqt::icons::antd
