#ifndef ADQT_ICONS_VERSION_H
#define ADQT_ICONS_VERSION_H

#define ADQT_ICONS_VERSION_MAJOR 0
#define ADQT_ICONS_VERSION_MINOR 1
#define ADQT_ICONS_VERSION_PATCH 0

#define ADQT_ICONS_VERSION_STR "0.1.0"

#endif  // ADQT_ICONS_VERSION_H
